#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan for RM2100

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/keke1023/Padavan.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: RM2100
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        
        #######最小化系统及更新设置#######################################################################
        cp -f $GITHUB_WORKSPACE/asus_logo.png                   user/www/n56u_ribbon_fixed/bootstrap/img/asus_logo.png   #替换logo
        cp -f $GITHUB_WORKSPACE/banner                          user/scripts/banner
        cp -f $GITHUB_WORKSPACE/ipt2socks/mtd_storage.sh        user/scripts/mtd_storage.sh
        cp -f $GITHUB_WORKSPACE/autostart.sh                    user/scripts/autostart.sh
        sed -i '/2011-2019/{s/2019/2025/}' user/www/Makefile    #过年好
        sed -i '3c FIRMWARE_BUILDS_REV=lissom' versions.inc     #更新版本
        sed -i '/INCLUDE/{s/=y/=n/}' .config                    #关闭所有INCLUDE
        sed -i '/SFE/{s/=n/=y/}' .config                        #开启SFE
        sed -i '/LANG_CN/{s/=n/=y/}' .config                    #设置默认语言为中文
        sed -i '/ENABLE_IPV6/{s/=n/=y/}' .config                #开启IPV6
        sed -i '898,899d' user/rc/net.c                         #修复ios访问bug
        echo "CONFIG_FIRMWARE_WEBUI_HIDE_VPN=y" >> .config      #VPN
        #######移除无用菜单#############################################################################
        rm -rf user/www/n56u_ribbon_fixed/vpn_clients.asp
        rm -rf user/www/n56u_ribbon_fixed/vpncli.asp
        rm -rf user/www/n56u_ribbon_fixed/vpnsrv.asp
        sed -i '594c menuL1_title = new Array("", "<#menu1#>", "", "", "", "<#menu4#>", "<#menu5_8#>", "<#menu5#>");' user/www/n56u_ribbon_fixed/state.js
        sed -i '595c menuL1_link = new Array("", "index.asp", "", "", "", "Main_TrafficMonitor_realtime.asp", "Advanced_System_Info.asp", "as.asp");' user/www/n56u_ribbon_fixed/state.js
        
        ######更新软件源码###############################################################################
        sed -i '/htop-3.0.5/{s/3.0.5/3.0.2/}' user/htop/Makefile                #更新htop
        sed -i '1c SRC_NAME=openssl-1.1.1w' libs/libssl/Makefile                #更新openssl
        mv libs/libssl/openssl-1.1.1k.patch libs/libssl/openssl-1.1.1w.patch
        
        ######恢复基础工具###############################################################################
        sed -i '/_OPENSS/{s/=n/=y/}' .config
        sed -i '/IPSET/{s/=n/=y/}' .config
        sed -i '/CURL/{s/=n/=y/}' .config
        sed -i '/HTOP/{s/=n/=y/}' .config
        sed -i '/SFTP/{s/=n/=y/}' .config         #SFTP文件访问
        
        #######添加ipt2socks#############################################################################
        rm -rf user/ipt2socks
        cp -rf $GITHUB_WORKSPACE/ipt2socks/  user/
        sed -i '163c dir_$(CONFIG_FIRMWARE_INCLUDE_IP2SOCKS)  += ipt2socks' user/Makefile
        echo "CONFIG_FIRMWARE_INCLUDE_IP2SOCKS=y" >> .config
        #######更新预编译dnsmasq##########################################################################
        #rm -rf user/dnsmasq
        #cp -rf $GITHUB_WORKSPACE/dnsmasq/  user/
        #######更新预编译dnsmasq2.9##########################################################################
        rm -rf user/dnsmasq/dnsmasq-2.8x
        git clone --depth=1 https://github.com/Yonsm/dnsmasq user/dnsmasq/dnsmasq-2.8x
        ######开始打包####################################################################################
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: RM2100-kvr-wing
        path: /opt/images
